Add student files

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,36 +1,49 @@
 version: 2.1
-
 commands:
   destroy-environment:
-    description: Destroy backend and frontend cloudformation stacks given a workflow ID.
+    description: Destroy back-end and front-end cloudformation stacks given a workflow ID.
     parameters:
-      workflow_id:
-        type: string      
+      # Add parameter here
+      back_end:
+        default: "bckend${CIRCLE_WORKFLOW_ID:0:7}"
+        type: string
     steps:
       - run:
-          name: Destroy environment << parameters.workflow_id >>
-          command: |
-            aws cloudformation delete-stack --stack-name udapeople-backend-<< parameters.workflow_id >>
-            aws cloudformation delete-stack --stack-name udapeople-frontend-<< parameters.workflow_id >>
-            aws s3 rb s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7} --force
+          name: Destroy environments
           when: on_fail
+          command: |
+            echo "DESTROY STACKS"
+            #aws s3 rm "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
+
+            aws cloudformation delete-stack --stack-name bckend${CIRCLE_WORKFLOW_ID:0:7}
+            aws cloudformation delete-stack --stack-name frntend${CIRCLE_WORKFLOW_ID:0:7}
+            #exit 1
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
+    parameters:
+      # Add parameter here     
     steps:
       - run:
           name: Revert migrations
+          # Add when this will run
+          when: on_fail
           command: |
-            success_migration=$(curl -H "token: ${MEMSTASH_TOKEN}" --request GET https://api.memstash.io/values/migration_key)
-            if ((success_migrations== true));
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=$(curl -H "token: cec89a7b-efb7-4073-a329-074f88fea64c" --request GET https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID})
+            echo 'the key: ' migration_${CIRCLE_WORKFLOW_ID}
+            echo "the id is: " $SUCCESS
+
+            if(( $SUCCESS==1 )); 
             then
-              cd backend
+              cd ~/project/backend
+              ls -la
               npm install
               npm run migrations:revert
+              exit 1
             fi
-          when: on_fail
-
 jobs:
+  # Build Front-end
   build-frontend:
     docker:
       - image: circleci/node:13.8.0
@@ -41,13 +54,16 @@ jobs:
       - run:
           name: Build front-end
           command: |
+            # Your code here
             cd frontend
             npm install
             npm run build
+
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
 
+  #Build Back-end
   build-backend:
     docker:
       - image: circleci/node:13.8.0
@@ -58,204 +74,161 @@ jobs:
       - run:
           name: Back-end build
           command: |
+             # Your code here
              cd backend
-             npm install 
+             npm install package.json
+             npm install
              npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
+  #Test Front-end
   test-frontend:
     docker:
+      # Docker image here
       - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
+      # Restore from cache
       - restore_cache:
-          keys: [test-frontend]
+          keys: [frontend-build]
+          # Your job code here
       - run:
-          name: Front-end test
+          name: test front-end
           command: |
             cd frontend
-            npm install
+            npm install jest
             npm run test
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: test-frontend
-                
+
+  #Test Back-end
   test-backend:
     docker:
+      # Docker image here
       - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
+      # Restore from cache
       - restore_cache:
-          keys: [test-backend]
+          keys: [backend-build]
+      # Your job code here
       - run:
-          name: Back-end test
+          name: test back-end
           command: |
             cd backend
-            npm install 
+            npm install jest
             npm run test
-      - save_cache:
-          paths: [backend/node_modules]
-          key: test-backend
-            
+
+  #Scan Front-end pacakages & security holes
   scan-frontend:
     docker:
+      # Docker image here
       - image: circleci/node:13.8.0
     steps:
+      # Checkout code from git
       - checkout
+      # Restore from cache
       - restore_cache:
-          keys: [scan-frontend]
+          keys: [frontend-build]
+      # Your job code here
       - run:
-          name: Front-end analyze
+          name: scan front-end
           command: |
             cd frontend
+            #npm audit fix
             npm audit fix --audit-level=critical --force
-      - save_cache:
-          paths: [frontend/node_modules]
-          key: scan-frontend
 
+  #Scan Back-end pacakages & security holes
   scan-backend:
     docker:
+      # Docker image here
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - restore_cache:
-          keys: [scan-backend]
+          keys: [backend-build]
+      # Your job code here
       - run:
-          name: Back-end analyze
+          name: scan back-end dependencies
           command: |
             cd backend
+            #npm audit fix
             npm audit fix --audit-level=critical --force
-      - save_cache:
-          paths: [backend/node_modules]
-          key: scan-backend
 
   deploy-infrastructure:
     docker:
       - image: amazon/aws-cli
+
     steps:
+      # Checkout code from git
       - checkout
       - run: yum -y install tar gzip
       - run:
           name: Ensure back-end infrastructure exists
           command: |
             aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              --tags project=udaPeople \
-              --stack-name "udapeople-backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
-      - run:
-          name: Ensure front-end infrastructure exist
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
-              --tags project=udaPeople \
-              --stack-name "udapeople-frontend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}"
+            --template-file .circleci/files/backend.yml \
+            --tags Project=udapeople \
+            --stack-name "bckend${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
+            --region=us-west-2
+
+      # Backend deploy infra
       - run:
           name: Add back-end ip to ansible inventory
           command: |
-            aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text >> .circleci/ansible/inventory.txt
-              cat .circleci/ansible/inventory.txt
+            serverIP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Project,Values=udapeople" --output text)
+            echo $serverIP >> .circleci/ansible/inventory.txt
+            curl -H "Content-Type: text/plain" -H "token: 2c4942df-cbd5-462a-9ca4-a60cccd9f0af" --request PUT --data "$serverIP" https://api.memstash.io/values/backendip
+            cat .circleci/ansible/inventory.txt
+
       - persist_to_workspace:
           root: ~/
           paths:
             - project/.circleci/ansible/inventory.txt
-            - project/backend/
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
+      #Store 
+      - run:
+          name: Backend ID
+          command: |
+            backendIP=$(curl -H "token: 2c4942df-cbd5-462a-9ca4-a60cccd9f0af" --request GET https://api.memstash.io/values/backendip)
+            echo "The IP is: " $backendIP
 
+      #Frontend deploy infra
+      - run:
+          name: Ensure front-end infrastructure exist
+          command: |
+            aws cloudformation deploy \
+            --template-file .circleci/files/frontend.yml \
+            --tags Project=udapeople \
+            --stack-name "frntend${CIRCLE_WORKFLOW_ID:0:7}" \
+            --parameter-overrides ID="${CIRCLE_WORKFLOW_ID:0:7}" \
+            --region=us-west-2
+
+      # Here's where you will add some code to rollback on failure
+      - destroy-environment
 
   configure-infrastructure:
     docker:
       - image: python:3.7-alpine3.11
     steps:
       - checkout
+      - add_ssh_keys:
+          fingerprints: ["28:ee:81:3a:67:68:8e:4d:82:8e:7c:42:58:42:75:5b"]
+
       - attach_workspace:
           at: ~/
-      - add_ssh_keys:
-          fingerprints: ["21:19:c0:15:0f:12:94:29:80:f0:01:51:c2:b3:e8:97"]
-      - run:
-          name: install dependencies
-          command: 
-            apk add --update ansible
-      - run:
-          name: Configure server
-          command: |
 
-            cd .circleci/ansible
-            ansible-playbook -i inventory.txt configure-server.yml
-
-  run-migrations:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - run:
-          name: run and save migration 
-          command: |
-            cd backend
-            npm install
-            npm audit fix --audit-level=critical --force
-            npm run migrations > migrations.txt
-            curl -H "Content-Type: text/plain" -H "token: ${MEMSTASH_TOKEN}" --request PUT --data "" https://api.memstash.io/values/migration_key
-            cat migrations.txt 
-          
-  deploy-frontend:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
-            yum -y install nodejs
-            yum -y install tar gzip
-      - run:    
-          name: Get backend url
-          command: |
-            export BACKEND_IP=$(aws ec2 describe-instances \
-              --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-              --query 'Reservations[*].Instances[*].PublicIpAddress' \
-              --output text)
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-      - run:
-          name: Deploy frontend 
-          command: |
-            cd frontend
-            npm install
-            npm run build
-            tar -czvf artifact-"${CIRCLE_WORKFLOW_ID:0:7}".tar.gz dist
-            aws s3 sync dist s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations
-
-  deploy-backend:
-    docker:
-      - image: python:3.7-alpine3.11
-    steps:
-      - checkout
-      - add_ssh_keys:
-          fingerprints: ["21:19:c0:15:0f:12:94:29:80:f0:01:51:c2:b3:e8:97"]
-      - attach_workspace:
-          at: ~/
       - run:
           name: Install dependencies
           command: |
             apk add --update tar gzip ansible nodejs npm
             pip install awscli
-      - run:
-          name: deploy backend
-          no_output_timeout: 30m
-          command: |
-            echo ENVIROMENT=development > "backend/.env"
+            echo PWD
+            pwd
+            touch backend/.env
+            echo ENVIRONMENT=production >> "backend/.env"
             echo TYPEORM_CONNECTION=postgres >> "backend/.env"
             echo TYPEORM_MIGRATIONS_DIR=./src/migrations >> "backend/.env"
             echo TYPEORM_ENTITIES=./src/modules/domain/**/*.entity.ts >> "backend/.env"
@@ -265,69 +238,77 @@ jobs:
             echo TYPEORM_USERNAME=$TYPEORM_USERNAME >> "backend/.env"
             echo TYPEORM_PASSWORD=$TYPEORM_PASSWORD >> "backend/.env"
             echo TYPEORM_DATABASE=$TYPEORM_DATABASE >> "backend/.env"
-            tar -C backend -czvf artifact.tar.gz .
-            cd .circleci/ansible
-            ansible-playbook -i inventory.txt deploy-backend.yml
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations
+            
+            ls -la backend
+            cat backend/.env
 
-  smoke-test:
+            cd ~/project/.circleci/ansible/
+            ansible-playbook -i inventory.txt configure-server.yml 
+            
+
+#      - run:
+#          name: Configure server
+#          command: |
+#            cd ~/project/.circleci/ansible/
+#            ansible-playbook -i inventory.txt configure-server.yml 
+            #exit 1
+      # Here's where you will add some code to rollback on failure      
+      - destroy-environment
+
+  run-migrations:
     docker:
-      - image: python:3.7-alpine3.11
+      - image: circleci/node:latest
     steps:
       - checkout
-      - attach_workspace:
-          at: ~/
+      #- amazoncli
+      - restore_cache:
+          keys: [backend-build]
+
       - run:
-          name: Install dependencies
+          name: awscli install
           command: |
-            apk add --update curl nodejs npm
-            pip install awscli
+            sudo apt-get -y -qq update
+            sudo apt-get -y -qq install python3
+            sudo apt-get -qq install awscli
+
       - run:
-          name: Frontend smoke test.
+          name: Run migrations
           command: |
-            URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3.website.us-west-2.amazonaws.com"            
-            if curl -s ${URL} | grep "Welcome"
+            cd backend && npm install
+            #npm run build
+            #npm audit fix --force
+            
+            cat .env
+            
+            echo 'DUMP MIGRATIONS'
+            echo 'hello world!!' > migrations_dump.txt
+            npm run migrations >> migrations_dump.txt
+            echo "I AM HERE!!" 
+            pwd
+            ls -la
+            
+            echo 'DISPLAY CONTENTS'
+            cat migrations_dump.txt
+            echo '*****************'
+            
+
+      - run:
+          name: Send migration results to memstash
+          command: |
+            if grep -q "has been executed successfully." ~/project/backend/migrations_dump.txt
             then
-              return 1
+              curl -H "Content-Type: text/plain" -H "token: cec89a7b-efb7-4073-a329-074f88fea64c" --request PUT --data "1" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+              echo migration_${CIRCLE_WORKFLOW_ID}
+              echo "1"
             else
-              return 0
+              curl -H "Content-Type: text/plain" -H "token: cec89a7b-efb7-4073-a329-074f88fea64c" --request PUT --data "0" https://api.memstash.io/values/migration_${CIRCLE_WORKFLOW_ID}
+              echo migration_${CIRCLE_WORKFLOW_ID}
+              echo "0"
             fi
-      - run:
-          name: backend url / backend smoke test.
-          command: |
-            BACKEND_IP=$(aws ec2 describe-instances \
-            --filters "Name=tag:Name, Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
-            --query 'Reservations[*].Instances[*].PublicIpAddress' \
-            --output text)
-            curl "https://${BACKEND_IP}:3030/api/status"
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations
+            exit 1
 
-  cloudfront-update:
-    docker:
-      - image: amazon/aws-cli
-    steps:
-      - checkout
-      - run:
-          name: Install dependencies
-          command: |
-            curl -sL https://rpm.nodesource.com/setup_lts.x | bash -
-            yum -y install nodejs
-            yum -y install tar gzip
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/cloudfront.yml \
-              --stack-name udapeople-cloudfront \
-              --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
-              --tags project=udapeople -
-      - destroy-environment:
-          workflow_id: ${CIRCLE_WORKFLOW_ID:0:7}
-      - revert-migrations 
+      #- revert-migrations
+      - destroy-environment
 
 workflows:
   default:
@@ -338,23 +319,13 @@ workflows:
           requires: [build-frontend]
       - test-backend:
           requires: [build-backend]
-      - scan-backend:
-          requires: [build-backend]
       - scan-frontend:
           requires: [build-frontend]
+      - scan-backend:
+          requires: [build-backend]
       - deploy-infrastructure:
           requires: [test-frontend, test-backend, scan-frontend, scan-backend]
       - configure-infrastructure:
           requires: [deploy-infrastructure]
       - run-migrations:
           requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-#      - cleanup:
-#          requires: [cloudfront-update]
